package com.passing.hibernate.beans;

/**
 * AbstractJpwordremark generated by MyEclipse Persistence Tools
 */

public abstract class AbstractJpwordremark implements java.io.Serializable {

	// Fields

	private Long id;
	private Jpword jpword;
	private String remark;

	// Constructors

	/** default constructor */
	public AbstractJpwordremark() {
	}

	/** full constructor */
	public AbstractJpwordremark(Jpword jpword, String remark) {
		this.jpword = jpword;
		this.remark = remark;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Jpword getJpword() {
		return this.jpword;
	}

	public void setJpword(Jpword jpword) {
		this.jpword = jpword;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}