package com.passing.hibernate.beans;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractJpwordmeaning generated by MyEclipse Persistence Tools
 */

public abstract class AbstractJpwordmeaning implements java.io.Serializable {

	// Fields

	private Long id;
	private Jpword jpword;
	private String meaning;
	private String partofspeech;
	private Set jpwordexamples = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractJpwordmeaning() {
	}

	/** minimal constructor */
	public AbstractJpwordmeaning(String meaning) {
		this.meaning = meaning;
	}

	/** full constructor */
	public AbstractJpwordmeaning(Jpword jpword, String meaning,
			String partofspeech, Set jpwordexamples) {
		this.jpword = jpword;
		this.meaning = meaning;
		this.partofspeech = partofspeech;
		this.jpwordexamples = jpwordexamples;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Jpword getJpword() {
		return this.jpword;
	}

	public void setJpword(Jpword jpword) {
		this.jpword = jpword;
	}

	public String getMeaning() {
		return this.meaning;
	}

	public void setMeaning(String meaning) {
		this.meaning = meaning;
	}

	public String getPartofspeech() {
		return this.partofspeech;
	}

	public void setPartofspeech(String partofspeech) {
		this.partofspeech = partofspeech;
	}

	public Set getJpwordexamples() {
		return this.jpwordexamples;
	}

	public void setJpwordexamples(Set jpwordexamples) {
		this.jpwordexamples = jpwordexamples;
	}

}