package com.passing.hibernate.beans;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractJpword generated by MyEclipse Persistence Tools
 */

public abstract class AbstractJpword implements java.io.Serializable {

	// Fields

	private Long id;
	private String kana;
	private String word;
	private Set jpwordmeanings = new HashSet(0);
	private Set jpwordremarks = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractJpword() {
	}

	/** minimal constructor */
	public AbstractJpword(String kana) {
		this.kana = kana;
	}

	/** full constructor */
	public AbstractJpword(String kana, String word, Set jpwordmeanings,
			Set jpwordremarks) {
		this.kana = kana;
		this.word = word;
		this.jpwordmeanings = jpwordmeanings;
		this.jpwordremarks = jpwordremarks;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getKana() {
		return this.kana;
	}

	public void setKana(String kana) {
		this.kana = kana;
	}

	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	public Set getJpwordmeanings() {
		return this.jpwordmeanings;
	}

	public void setJpwordmeanings(Set jpwordmeanings) {
		this.jpwordmeanings = jpwordmeanings;
	}

	public Set getJpwordremarks() {
		return this.jpwordremarks;
	}

	public void setJpwordremarks(Set jpwordremarks) {
		this.jpwordremarks = jpwordremarks;
	}

}