package com.passing.hibernate.beans;

import java.util.Date;


/**
 * AbstractPassingUser generated by MyEclipse Persistence Tools
 */

public abstract class AbstractPassingUser  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String username;
     private String password;
     private String nickname;
     private String emailaddress;
     private Long sex;
     private Date birthday;
     private String fgtpwdproblem;
     private String fgtpwdanswer;
     private String country;
     private String city;
     private String university;
     private String technicalschool;
     private String highschool;
     private String middleschool;
     private String elementaryschool;
     private String company;
     private Long qq;
     private String msn;
     private Long telphone;
     private String personalweb;


    // Constructors

    /** default constructor */
    public AbstractPassingUser() {
    }

	/** minimal constructor */
    public AbstractPassingUser(String username, String password, String emailaddress, Long sex) {
        this.username = username;
        this.password = password;
        this.emailaddress = emailaddress;
        this.sex = sex;
    }
    
    /** full constructor */
    public AbstractPassingUser(String username, String password, String nickname, String emailaddress, Long sex, Date birthday, String fgtpwdproblem, String fgtpwdanswer, String country, String city, String university, String technicalschool, String highschool, String middleschool, String elementaryschool, String company, Long qq, String msn, Long telphone, String personalweb) {
        this.username = username;
        this.password = password;
        this.nickname = nickname;
        this.emailaddress = emailaddress;
        this.sex = sex;
        this.birthday = birthday;
        this.fgtpwdproblem = fgtpwdproblem;
        this.fgtpwdanswer = fgtpwdanswer;
        this.country = country;
        this.city = city;
        this.university = university;
        this.technicalschool = technicalschool;
        this.highschool = highschool;
        this.middleschool = middleschool;
        this.elementaryschool = elementaryschool;
        this.company = company;
        this.qq = qq;
        this.msn = msn;
        this.telphone = telphone;
        this.personalweb = personalweb;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getEmailaddress() {
        return this.emailaddress;
    }
    
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }

    public Long getSex() {
        return this.sex;
    }
    
    public void setSex(Long sex) {
        this.sex = sex;
    }

    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getFgtpwdproblem() {
        return this.fgtpwdproblem;
    }
    
    public void setFgtpwdproblem(String fgtpwdproblem) {
        this.fgtpwdproblem = fgtpwdproblem;
    }

    public String getFgtpwdanswer() {
        return this.fgtpwdanswer;
    }
    
    public void setFgtpwdanswer(String fgtpwdanswer) {
        this.fgtpwdanswer = fgtpwdanswer;
    }

    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getUniversity() {
        return this.university;
    }
    
    public void setUniversity(String university) {
        this.university = university;
    }

    public String getTechnicalschool() {
        return this.technicalschool;
    }
    
    public void setTechnicalschool(String technicalschool) {
        this.technicalschool = technicalschool;
    }

    public String getHighschool() {
        return this.highschool;
    }
    
    public void setHighschool(String highschool) {
        this.highschool = highschool;
    }

    public String getMiddleschool() {
        return this.middleschool;
    }
    
    public void setMiddleschool(String middleschool) {
        this.middleschool = middleschool;
    }

    public String getElementaryschool() {
        return this.elementaryschool;
    }
    
    public void setElementaryschool(String elementaryschool) {
        this.elementaryschool = elementaryschool;
    }

    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    public Long getQq() {
        return this.qq;
    }
    
    public void setQq(Long qq) {
        this.qq = qq;
    }

    public String getMsn() {
        return this.msn;
    }
    
    public void setMsn(String msn) {
        this.msn = msn;
    }

    public Long getTelphone() {
        return this.telphone;
    }
    
    public void setTelphone(Long telphone) {
        this.telphone = telphone;
    }

    public String getPersonalweb() {
        return this.personalweb;
    }
    
    public void setPersonalweb(String personalweb) {
        this.personalweb = personalweb;
    }
   








}