package com.passing.hibernate.beans;

/**
 * AbstractJpwordexample generated by MyEclipse Persistence Tools
 */

public abstract class AbstractJpwordexample implements java.io.Serializable {

	// Fields

	private Long id;
	private Jpwordmeaning jpwordmeaning;
	private String example;
	private String examplemeaning;

	// Constructors

	/** default constructor */
	public AbstractJpwordexample() {
	}

	/** full constructor */
	public AbstractJpwordexample(Jpwordmeaning jpwordmeaning, String example,
			String examplemeaning) {
		this.jpwordmeaning = jpwordmeaning;
		this.example = example;
		this.examplemeaning = examplemeaning;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Jpwordmeaning getJpwordmeaning() {
		return this.jpwordmeaning;
	}

	public void setJpwordmeaning(Jpwordmeaning jpwordmeaning) {
		this.jpwordmeaning = jpwordmeaning;
	}

	public String getExample() {
		return this.example;
	}

	public void setExample(String example) {
		this.example = example;
	}

	public String getExamplemeaning() {
		return this.examplemeaning;
	}

	public void setExamplemeaning(String examplemeaning) {
		this.examplemeaning = examplemeaning;
	}

}