package com.passing.hibernate.beans;

import java.util.Set;

/**
 * Jpwordmeaning generated by MyEclipse Persistence Tools
 */
public class Jpwordmeaning extends AbstractJpwordmeaning implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public Jpwordmeaning() {
	}

	/** minimal constructor */
	public Jpwordmeaning(String meaning) {
		super(meaning);
	}

	/** full constructor */
	public Jpwordmeaning(Jpword jpword, String meaning, String partofspeech,
			Set jpwordexamples) {
		super(jpword, meaning, partofspeech, jpwordexamples);
	}

}
