package com.passing.hibernate.beans;

/**
 * Jpwordexample generated by MyEclipse Persistence Tools
 */
public class Jpwordexample extends AbstractJpwordexample implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public Jpwordexample() {
	}

	/** full constructor */
	public Jpwordexample(Jpwordmeaning jpwordmeaning, String example,
			String examplemeaning) {
		super(jpwordmeaning, example, examplemeaning);
	}

}
