package com.passing.hibernate.beans;

/**
 * Jpwordremark generated by MyEclipse Persistence Tools
 */
public class Jpwordremark extends AbstractJpwordremark implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public Jpwordremark() {
	}

	/** full constructor */
	public Jpwordremark(Jpword jpword, String remark) {
		super(jpword, remark);
	}

}
