package com.passing.hibernate.beans;

import java.util.Date;


/**
 * PassingUser generated by MyEclipse Persistence Tools
 */
public class PassingUser extends AbstractPassingUser implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public PassingUser() {
    }

	/** minimal constructor */
    public PassingUser(String username, String password, String emailaddress, Long sex) {
        super(username, password, emailaddress, sex);        
    }
    
    /** full constructor */
    public PassingUser(String username, String password, String nickname, String emailaddress, Long sex, Date birthday, String fgtpwdproblem, String fgtpwdanswer, String country, String city, String university, String technicalschool, String highschool, String middleschool, String elementaryschool, String company, Long qq, String msn, Long telphone, String personalweb) {
        super(username, password, nickname, emailaddress, sex, birthday, fgtpwdproblem, fgtpwdanswer, country, city, university, technicalschool, highschool, middleschool, elementaryschool, company, qq, msn, telphone, personalweb);        
    }
   
}
