package com.passing.hibernate.beans;

/**
 * PassingUser generated by MyEclipse Persistence Tools
 */
public class TbEnFrequency extends AbstractTbEnFrequency implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** default constructor */
    public TbEnFrequency() {
    }
    
    /** full constructor */
    public TbEnFrequency(int word_id, String word, int frequency) {
        super(word_id, word, frequency);
    }
   
}
